# Generated by Django 4.1.5 on 2023-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0003_alter_gamemodel_id_alter_gamerlibrarymodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='year',
            field=models.CharField(max_length=64),
        ),
    ]
