# Generated by Django 4.1.5 on 2023-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0004_alter_gamemodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='year',
            field=models.DateField(),
        ),
    ]
