# Generated by Django 4.1.5 on 2023-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0005_alter_gamemodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na_sales', models.FloatField()),
                ('eu_sales', models.FloatField()),
                ('jp_sales', models.FloatField()),
            ],
        ),
    ]
