# Generated by Django 4.1.5 on 2023-01-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_8', '0006_gamemodel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameModel2',
        ),
    ]
